import { prisma } from "../../prisma";
import {
  DashboardFilters,
  getSummary,
  getSalaryByDepartment,
  getNetSalaryTrend,
  getAttendanceOverview,
  getAlerts,
} from "../dashboard/dashboard.service";

export interface PayrollReportData {
  generatedAt: Date;
  generatedBy: string;
  filters: DashboardFilters;
  departmentName: string | null;
  summary: Awaited<ReturnType<typeof getSummary>>;
  salaryByDepartment: Awaited<ReturnType<typeof getSalaryByDepartment>>;
  netSalaryTrend: Awaited<ReturnType<typeof getNetSalaryTrend>>;
  attendance: Awaited<ReturnType<typeof getAttendanceOverview>>;
  alerts: Awaited<ReturnType<typeof getAlerts>>;
  payruns: {
    periodStart: Date;
    periodEnd: Date;
    status: string;
    structureName: string;
    payslipCount: number;
    netTotal: number;
  }[];
}

// One aggregation pass shared by both the PDF and the CSV export, so the two can never
// disagree about the same period's numbers — the report is assembled once and rendered twice.
export async function buildPayrollReport(
  filters: DashboardFilters,
  generatedByUserId: string
): Promise<PayrollReportData> {
  const [summary, salaryByDepartment, netSalaryTrend, attendance, alerts, payrunRows, department, author] = await Promise.all([
    getSummary(filters, true),
    getSalaryByDepartment(filters),
    getNetSalaryTrend(filters),
    getAttendanceOverview(filters),
    getAlerts(filters),
    prisma.payrun.findMany({
      where:
        filters.periodStart || filters.periodEnd
          ? {
              periodStart: filters.periodEnd ? { lte: filters.periodEnd } : undefined,
              periodEnd: filters.periodStart ? { gte: filters.periodStart } : undefined,
            }
          : undefined,
      include: { structure: { select: { name: true } }, payslips: { select: { net: true } } },
      orderBy: { periodStart: "desc" },
    }),
    filters.departmentId
      ? prisma.department.findUnique({ where: { id: filters.departmentId }, select: { name: true } })
      : Promise.resolve(null),
    prisma.user.findUnique({
      where: { id: generatedByUserId },
      select: { email: true, employee: { select: { name: true } } },
    }),
  ]);

  return {
    generatedAt: new Date(),
    generatedBy: author?.employee?.name ?? author?.email ?? "Unknown user",
    filters,
    departmentName: department?.name ?? null,
    summary,
    salaryByDepartment,
    netSalaryTrend,
    attendance,
    alerts,
    payruns: payrunRows.map((p) => ({
      periodStart: p.periodStart,
      periodEnd: p.periodEnd,
      status: p.status,
      structureName: p.structure?.name ?? "—",
      payslipCount: p.payslips.length,
      netTotal: p.payslips.reduce((sum, s) => sum + Number(s.net), 0),
    })),
  };
}

// RFC 4180 quoting: wrap in quotes and double any embedded quote. Without this a
// department named 'Sales, EMEA' silently shifts every following column.
function csvCell(value: unknown): string {
  const s = value === null || value === undefined ? "" : String(value);
  return `"${s.replace(/"/g, '""')}"`;
}

function csvSection(title: string, headers: string[], rows: (string | number)[][]): string[] {
  return [
    csvCell(title),
    headers.map(csvCell).join(","),
    ...rows.map((r) => r.map(csvCell).join(",")),
    "",
  ];
}

export function renderPayrollReportCsv(data: PayrollReportData): string {
  const s = data.summary as Record<string, unknown>;
  const lines: string[] = [
    csvCell("PeoplePay360 — Payroll Report"),
    `${csvCell("Generated")},${csvCell(data.generatedAt.toISOString())}`,
    `${csvCell("Generated by")},${csvCell(data.generatedBy)}`,
    `${csvCell("Department")},${csvCell(data.departmentName ?? "All departments")}`,
    "",
    ...csvSection(
      "Summary",
      ["Metric", "Value"],
      [
        ["Total Net Paid", Number(s.totalNetPaid ?? 0)],
        ["Payslips Generated", Number(s.payslipsGenerated ?? 0)],
        ["Average Salary", Number(s.averageSalary ?? 0)],
        ["Approved Time Off", Number(s.approvedTimeOff ?? 0)],
        ["Attendance Health %", Number(s.attendanceHealthPct ?? 0)],
      ]
    ),
    ...csvSection(
      "Salary by Department",
      ["Department", "Headcount", "Total Salary"],
      data.salaryByDepartment.map((d) => [d.departmentName, d.headcount, d.totalSalary])
    ),
    ...csvSection(
      "Monthly Net Salary Trend",
      ["Month", "Net Total"],
      data.netSalaryTrend.map((t) => [t.month, t.netTotal])
    ),
    ...csvSection(
      "Payruns",
      ["Period Start", "Period End", "Structure", "Status", "Payslips", "Net Total"],
      data.payruns.map((p) => [
        p.periodStart.toISOString().slice(0, 10),
        p.periodEnd.toISOString().slice(0, 10),
        p.structureName,
        p.status,
        p.payslipCount,
        p.netTotal,
      ])
    ),
  ];

  return lines.join("\r\n");
}
